---
kind: pipeline
type: docker
name: build-aarch64

platform:
  arch: arm64
  os: linux

steps:
  - name: build-jammy
    image: plugins/docker
    settings:
      repo: andreipoe/buildpack-ubuntu
      tags:
        - jammy-aarch64
        - 22.04-aarch64
      dockerfile: jammy/Dockerfile
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
    when:
      status: [success, failure]
  - name: build-noble
    image: plugins/docker
    settings:
      repo: andreipoe/buildpack-ubuntu
      tags:
        - noble-aarch64
        - 24.04-aarch64
        - latest-aarch64
      dockerfile: noble/Dockerfile
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
    when:
      status: [success, failure]

---
kind: pipeline
type: docker
name: build-amd64

platform:
  arch: amd64
  os: linux

steps:
  - name: build-jammy
    image: plugins/docker
    settings:
      repo: andreipoe/buildpack-ubuntu
      tags:
        - jammy-amd64
        - 22.04-amd64
      dockerfile: jammy/Dockerfile
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
    when:
      status: [success, failure]
  - name: build-noble
    image: plugins/docker
    settings:
      repo: andreipoe/buildpack-ubuntu
      tags:
        - noble-amd64
        - 24.04-amd64
        - latest-amd64
      dockerfile: noble/Dockerfile
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
    when:
      status: [success, failure]

---
kind: pipeline
type: docker
name: multiarch-manifest

steps:
  - name: manifest-jammy
    image: plugins/manifest
    settings:
      spec: jammy/manifest-spec.yml
      username: andreipoe
      password:
        from_secret: docker_token
  - name: manifest-noble
    image: plugins/manifest
    settings:
      spec: noble/manifest-spec.yml
      username: andreipoe
      password:
        from_secret: docker_token
  - name: healthcheck
    image: ubuntu
    environment:
      HEALTHCHECKS_URL:
        from_secret: healthchecks_url
    commands:
      - apt-get update
      - apt-get -y install curl
      - |
        if [ ${DRONE_BUILD_STATUS} = success ]; then
          curl --retry 3 $${HEALTHCHECKS_URL}
        else
          curl --retry 3 $${HEALTHCHECKS_URL}/fail
        fi
    when:
      status: [success, failure]

depends_on: [build-aarch64, build-amd64]
trigger:
  status: [success, failure]

---
kind: signature
hmac: ef9baf56f929ce242dd0c91b8a2b396f3fd2cf781bea303a4dd73e9c5c25f62d

...
