---
kind: pipeline
type: docker
name: build-aarch64

platform:
  arch: arm64
  os: linux

steps:
  - name: build-xenial
    image: plugins/docker
    settings:
      repo: andreipoe/buildpack-ubuntu
      tags:
        - xenial-aarch64
        - 16.04-aarch64
      dockerfile: xenial/Dockerfile
      username: andreipoe
      password:
        from_secret: docker_token
  - name: build-bionic
    image: plugins/docker
    settings:
      repo: andreipoe/buildpack-ubuntu
      tags:
        - bionic-aarch64
        - 18.04-aarch64
        - latest-aarch64
      dockerfile: bionic/Dockerfile
      username: andreipoe
      password:
        from_secret: docker_token
    when:
      status: [success, failure]

---
kind: pipeline
type: docker
name: build-amd64

platform:
  arch: amd64
  os: linux

steps:
  - name: build-xenial
    image: plugins/docker
    settings:
      repo: andreipoe/buildpack-ubuntu
      tags:
        - xenial-amd64
        - 16.04-amd64
      dockerfile: xenial/Dockerfile
      username: andreipoe
      password:
        from_secret: docker_token
  - name: build-bionic
    image: plugins/docker
    settings:
      repo: andreipoe/buildpack-ubuntu
      tags:
        - bionic-amd64
        - 18.04-amd64
        - latest-amd64
      dockerfile: bionic/Dockerfile
      username: andreipoe
      password:
        from_secret: docker_token
    when:
      status: [success, failure]

---
kind: pipeline
type: docker
name: multiarch-manifest

steps:
  - name: manifest-xenial
    image: plugins/manifest
    settings:
      target: andreipoe/buildpack-ubuntu
      spec: xenial/manifest-spec.yml
      username: andreipoe
      password:
        from_secret: docker_token
  - name: manifest-bionic
    image: plugins/manifest
    settings:
      target: andreipoe/buildpack-ubuntu
      spec: bionic/manifest-spec.yml
      username: andreipoe
      password:
        from_secret: docker_token

depends_on: [build-aarch64, build-amd64]
trigger:
  status: [success, failure]

---
kind: signature
hmac: 2ff644eb789c39e8cb8e2f39b8511edb10d8d92638a26a57c5f3673da854fc49

...
