---
kind: pipeline
type: docker
name: build-aarch64

platform:
  arch: arm64
  os: linux

steps:
  - name: build-xenial
    image: plugins/docker
    settings:
      repo: andreipoe/buildpack-ubuntu
      tags:
        - xenial-aarch64
        - 16.04-aarch64
      dockerfile: xenial/Dockerfile
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
  - name: build-bionic
    image: plugins/docker
    settings:
      repo: andreipoe/buildpack-ubuntu
      tags:
        - bionic-aarch64
        - 18.04-aarch64
      dockerfile: bionic/Dockerfile
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
    when:
      status: [success, failure]
  - name: build-focal
    image: plugins/docker
    settings:
      repo: andreipoe/buildpack-ubuntu
      tags:
        - focal-aarch64
        - 20.04-aarch64
      dockerfile: focal/Dockerfile
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
    when:
      status: [success, failure]
  - name: build-jammy
    image: plugins/docker
    settings:
      repo: andreipoe/buildpack-ubuntu
      tags:
        - jammy-aarch64
        - 22.04-aarch64
        - latest-aarch64
      dockerfile: jammy/Dockerfile
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
    when:
      status: [success, failure]

---
kind: pipeline
type: docker
name: build-amd64

platform:
  arch: amd64
  os: linux

steps:
  - name: build-xenial
    image: plugins/docker
    settings:
      repo: andreipoe/buildpack-ubuntu
      tags:
        - xenial-amd64
        - 16.04-amd64
      dockerfile: xenial/Dockerfile
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
  - name: build-bionic
    image: plugins/docker
    settings:
      repo: andreipoe/buildpack-ubuntu
      tags:
        - bionic-amd64
        - 18.04-amd64
      dockerfile: bionic/Dockerfile
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
    when:
      status: [success, failure]
  - name: build-focal
    image: plugins/docker
    settings:
      repo: andreipoe/buildpack-ubuntu
      tags:
        - focal-amd64
        - 20.04-amd64
      dockerfile: focal/Dockerfile
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
    when:
      status: [success, failure]
  - name: build-jammy
    image: plugins/docker
    settings:
      repo: andreipoe/buildpack-ubuntu
      tags:
        - jammy-amd64
        - 22.04-amd64
        - latest-amd64
      dockerfile: jammy/Dockerfile
      username: andreipoe
      password:
        from_secret: docker_token
    depends_on: [clone]
    when:
      status: [success, failure]

---
kind: pipeline
type: docker
name: multiarch-manifest

steps:
  - name: manifest-xenial
    image: plugins/manifest
    settings:
      target: andreipoe/buildpack-ubuntu
      spec: xenial/manifest-spec.yml
      username: andreipoe
      password:
        from_secret: docker_token
  - name: manifest-bionic
    image: plugins/manifest
    settings:
      target: andreipoe/buildpack-ubuntu
      spec: bionic/manifest-spec.yml
      username: andreipoe
      password:
        from_secret: docker_token
  - name: manifest-focal
    image: plugins/manifest
    settings:
      target: andreipoe/buildpack-ubuntu
      spec: focal/manifest-spec.yml
      username: andreipoe
      password:
        from_secret: docker_token
  - name: manifest-jammy
    image: plugins/manifest
    settings:
      target: andreipoe/buildpack-ubuntu
      spec: jammy/manifest-spec.yml
      username: andreipoe
      password:
        from_secret: docker_token

depends_on: [build-aarch64, build-amd64]
trigger:
  status: [success, failure]

---
kind: signature
hmac: 878ecf4a10199612ec5fa24c16ecd11aca3778461d10f44474be9af03386685d

...
